# .github/workflows/deploy.yml
name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WASM
        run: dotnet publish ./PhantomAirInvite.csproj -c Release -o dist

      # We upload dist/wwwroot (Blazor’s static output)
      - name: List outputs (debug)
        run: |
          echo "Listing dist:"
          ls -la dist
          echo "Listing dist/wwwroot:"
          ls -la dist/wwwroot || true

      - name: Ensure .nojekyll exists   # 👈 CRITICAL
        run: touch dist/wwwroot/.nojekyll

      - name: Add 404.html for client routing
        run: cp dist/wwwroot/index.html dist/wwwroot/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/wwwroot

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
