# .github/workflows/deploy.yml
name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PUBLISH_DIR: build/wwwroot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 👉 Publish to a fixed folder: build/
      - name: Publish Blazor WASM
        run: dotnet publish ./PhantomAirInvite.csproj -c Release -o build

      - name: Debug output
        run: |
          echo "Listing build:"
          ls -la build || true
          echo "Listing build/wwwroot:"
          ls -la build/wwwroot || true

      # Required so _framework files are not blocked by Jekyll
      - name: Ensure .nojekyll exists
        run: touch $PUBLISH_DIR/.nojekyll

      # SPA routing: make 404.html = index.html
      - name: Add 404.html for client routing
        run: cp $PUBLISH_DIR/index.html $PUBLISH_DIR/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
